version: '3.8'

services:
  rag-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      # Veri dosyasını bağla
      - ./Book1.json:/app/Book1.json
      - ./document.pdf:/app/document.pdf
      # Model ve indeks önbelleklerini kalıcı hale getir
      - model_cache:/app/model_cache
      - embedding_cache:/app/embedding_cache
      - storage:/app/storage
    environment:
      - PYTHONUNBUFFERED=1
      - NVIDIA_VISIBLE_DEVICES=all  # Tüm GPU'ları görünür yap
      - PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:256  # CUDA bellek ayarları
    restart: unless-stopped
    # GPU desteği ve kaynak sınırlamaları
    deploy:
      resources:
        limits:
          memory: 32G  # Bellek sınırını artır
        reservations:
          devices:
            - driver: nvidia
              count: 2  # İki GPU kullan
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # Başlangıç süresini artır

volumes:
  model_cache:
  embedding_cache:
  storage: 